//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFunctionality
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserRegistration
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> CSharp { get; set; }
        public Nullable<bool> Java { get; set; }
        public Nullable<bool> Python { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Image { get; set; }
    }
}
