//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSideValidation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Category
    {
        
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Category name must required")]
        //[StringLength(20,MinimumLength = 5,ErrorMessage = "Category length not match")]
        [RegularExpression("^[a-zA-Z]{3,10}$",ErrorMessage = "Invalid Category Name")]
        public string CategoryName { get; set; }

        [Required(ErrorMessage = "Description must required")]
        public string Description { get; set; }


        [Required(ErrorMessage = "Password must required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Confirm Password must required")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string CPassword { get; set; }
     
    }
}
